apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: chaewon0720/portal:welcome
        resources:
          limits:
            memory: "32Mi"
            cpu: "125m"
        ports:
        - containerPort: 80
